sequenceDiagram
  participant User as User Device
  participant Stub as OS Stub Resolver
  participant Rec as Recursive Resolver
  participant Root as Root Server
  participant TLD as TLD Server
  participant Auth as Authoritative DNS Server
  participant CDN as CDN/WAF

  User->>Stub: Send DNS Query
  Stub-->>Stub: Check Local Cache
  Stub->>Rec: Forward Query if Cache Miss
  Rec-->>Rec: Check Cache
  Rec->>Root: Query Root Server
  Root-->>Rec: Respond with TLD Reference
  Rec->>TLD: Query TLD Server
  TLD-->>Rec: Respond with Auth DNS Reference
  Rec->>Auth: Query Authoritative DNS
  Note right of Auth: Validate DNSSEC RRSIG
  Auth-->>Rec: Respond with DNS Record
  Rec-->>Stub: Forward Response
  Stub-->>User: Provide Answer to Query
  User->>CDN: Request Resource
  CDN-->>User: Provide Content

  Note left of Root: Test